# Generated by Django 6.1.1 on 2026-09-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('category', models.CharField(choices=[('omrani', 'عمرانی'), ('amoozeshi', 'آموزشی'), ('manfaati', 'عام\u200cالمنفعه'), ('parvareshi', 'پرورشی')], max_length=20, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='تصویر')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
                'ordering': ['-date'],
            },
        ),
    ]
