# Generated by Django 6.1.1 on 2026-10-02 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='مسئول خوابگاه')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dormitory/', verbose_name='تصویر اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'خوابگاه',
                'verbose_name_plural': 'خوابگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام بلوک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='مسئول بلوک')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='about.dormitory', verbose_name='خوابگاه')),
            ],
            options={
                'verbose_name': 'بلوک',
                'verbose_name_plural': 'بلوک\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='شماره سوییت')),
                ('capacity', models.PositiveIntegerField(default=6, verbose_name='ظرفیت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='suites/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='about.block', verbose_name='بلوک')),
            ],
            options={
                'verbose_name': 'سوییت',
                'verbose_name_plural': 'سوییت\u200cها',
                'ordering': ['order', 'number'],
            },
        ),
    ]
