# Generated by Django 6.1.1 on 2026-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: دانش\u200cآموز', max_length=100, verbose_name='عنوان')),
                ('value', models.CharField(help_text='مثلاً: ۵۰۰+', max_length=50, verbose_name='مقدار')),
                ('icon', models.CharField(choices=[('bi-people-fill', 'دانش\u200cآموزان'), ('bi-person-badge', 'دبیران'), ('bi-book', 'کتاب/رشته'), ('bi-trophy', 'افتخارات'), ('bi-building', 'ساختمان'), ('bi-mortarboard-fill', 'فارغ\u200cالتحصیلان'), ('bi-award', 'جوایز'), ('bi-star-fill', 'ستاره')], default='bi-people-fill', max_length=50, verbose_name='آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'آمار صفحه اصلی',
                'verbose_name_plural': 'آمار صفحه اصلی',
                'ordering': ['order'],
            },
        ),
    ]
